# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: vardan.pro
profile: >-
  Software development and DevOps
email: me@vardan.pro
description: >- # this means to ignore newlines until "baseurl:"
  Vardan Pogosian is Software developer and IT consultant. Love Go, Ruby and JS.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vardan.pro" # the base hostname & protocol for your site, e.g. http://example.com

author: Vardan Pogosian

twitter_username: varpt
github_username:  varp

disqus:
  shortname: vardanpro

# custom
vkontakte_username: dark_vardan
instagram_username: warrpp
facebook_username: dark.vardan

google_analytics: UA-58459838-1
yandex_metrika: 30353457

vardanpro:
  date_format: "%d.%m.%Y"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
